### PR TITLE
Create print_italics.md

### PR DESCRIPTION
**Pull request by gerrishons**
Print in italics now made easy!!

### CODE REVIEW

**Review by nonunicorn — CHANGES_REQUESTED** [review]
Hi sir, thank you!

Can you please add [explanations blocks](https://github.com/nonunicorn/onelinerhub/blob/main/template.md) and example blocks, so the code is well understood by newbies.

Thank you!

**Review by gerrishons — COMMENTED** [review]
Added a few comments for newbies

**Comment by nonunicorn** [comment]
Thank you sir.

Please also help me test this code, currently I'm getting this error when trying to launch it using `python test.py` (file with your code) cmd:
```
/usr/bin/python: can't find '__main__' module in 'test'
```

**Comment by gerrishons** [comment]
Screenshot_20210720-122354
@nonunicorn the code only works with Python3.6+. You're using Python2.7

**Review by gerrishons — COMMENTED** [review]
Added a shebang

**Comment by nonunicorn** [comment]
Thanks.

Now we see the following error (`pip` is not installed in the testing environment):
```
./test.py 
Requirement already satisfied: quo in /usr/local/lib/python3.8/dist-packages (2021.3)
Traceback (most recent call last):
  File "./test.py", line 6, in <module>
    import quo
  File "/usr/local/lib/python3.8/dist-packages/quo/__init__.py", line 10, in <module>
    from .application import Application
  File "/usr/local/lib/python3.8/dist-packages/quo/application/__init__.py", line 1, in <module>
    from .application import Application
  File "/usr/local/lib/python3.8/dist-packages/quo/application/application.py", line 42, in <module>
    from quo.buffer import Buffer
  File "/usr/local/lib/python3.8/dist-packages/quo/buffer.py", line 32, in <module>
    from .application.run_in_terminal import run_in_terminal
  File "/usr/local/lib/python3.8/dist-packages/quo/application/run_in_terminal.py", line 7, in <module>
    from quo.eventloop import run_in_executor_with_context
  File "/usr/local/lib/python3.8/dist-packages/quo/eventloop/__init__.py", line 2, in <module>
    from .inputhook import (
  File "/usr/local/lib/python3.8/dist-packages/quo/eventloop/inputhook.py", line 34, in <module>
    from quo.utils import is_windows
  File "/usr/local/lib/python3.8/dist-packages/quo/utils.py", line 19, in <module>
    from wcwidth import wcwidth
ModuleNotFoundError: No module named 'wcwidth'
```

**Review by gerrishons — COMMENTED** [review]
@nonunicorn added a few modifications. Copy this code and try again. This should work

**Comment by nonunicorn** [comment]
Thanks sir!

Sorry to say, but at this moment, this solution doesn't comply with our principles - be the shortest and the most simple of all possible solutions. Outputting italic text in console can be as easy as the solution suggested by one of our users:

https://onelinerhub.com/bash/italic_text

Still, your effort is very appreciated. Feel free to update your code to make it solve unique problem the shortest possible way.

**Pull request closed without merging**
