### PR TITLE
Create NameserverLookup.md

### PR DESCRIPTION
**Pull request by trojan0x**
# The snippet uses net.LookupNS() function  which takes a domain name as a string and returns its DNS-NS records

### CODE REVIEW

**Review by nonunicorn — CHANGES_REQUESTED** [review]
Hi sir!

Thank you for the submitted code.
Can you please check if the code block has closing entity, can't see it there.

Thank you!

**Review by trojan0x — COMMENTED** [review]
Inserted a closing entity to the codeblock

**Comment by trojan0x** [comment]
> Hi sir!
> 
> Thank you for the submitted code.
> Can you please check if the code block has closing entity, can't see it there.
> 
>Sorry bout that, have done that

**Comment by nonunicorn** [comment]
Perfect, thank you sir!

Made couple of minor edits to improve explanation block:
https://onelinerhub.com/golang/NameserverLookup

**Pull request merged**
